#ifndef CONST_H_INCLUDED
#define CONST_H_INCLUDED

enum ConnectStatus {NOT_CONNECTED, USER, ADMIN};
enum Choice {EXIT, BROWSE, SEARCH, LOGIN, ADD_TO_CART, REMOVE_FROM_CART, PAY, CREATE_COURSE, ASSIGN_COURSE, NONE};

#endif // CONST_H_INCLUDED
